export type Sale = {
  id: string;
  date: string; // YYYY-MM-DD
  product: string;
  category: string;
  clientType: "Mujer" | "Hombre" | "Niño" | "Niña";
  size: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  branch: "Sucursal A" | "Sucursal B" | "Sucursal C";
};

export const salesData: Sale[] = [
  {
    id: "1",
    date: "2025-10-01",
    product: "ABRIGO",
    category: "Abrigos",
    clientType: "Mujer",
    size: "M",
    quantity: 2,
    unitPrice: 120,
    totalPrice: 240,
    branch: "Sucursal A",
  },
  {
    id: "2",
    date: "2025-10-01",
    product: "JEANS TERMINADOS",
    category: "Pantalones",
    clientType: "Hombre",
    size: "L",
    quantity: 3,
    unitPrice: 80,
    totalPrice: 240,
    branch: "Sucursal B",
  },
  {
    id: "3",
    date: "2025-10-02",
    product: "TSHIRT TERMINADA",
    category: "T-Shirts",
    clientType: "Niño",
    size: "8",
    quantity: 5,
    unitPrice: 25,
    totalPrice: 125,
    branch: "Sucursal A",
  },
  {
    id: "4",
    date: "2025-10-02",
    product: "VESTIDOS",
    category: "Vestidos",
    clientType: "Niña",
    size: "10",
    quantity: 2,
    unitPrice: 60,
    totalPrice: 120,
    branch: "Sucursal C",
  },
  {
    id: "5",
    date: "2025-10-03",
    product: "BUZO",
    category: "Buzos",
    clientType: "Hombre",
    size: "XL",
    quantity: 1,
    unitPrice: 90,
    totalPrice: 90,
    branch: "Sucursal B",
  },
  {
    id: "6",
    date: "2025-10-03",
    product: "FALDA",
    category: "Faldas",
    clientType: "Mujer",
    size: "S",
    quantity: 4,
    unitPrice: 50,
    totalPrice: 200,
    branch: "Sucursal A",
  },
  {
    id: "7",
    date: "2025-10-04",
    product: "POLOS",
    category: "Polos",
    clientType: "Niño",
    size: "6",
    quantity: 10,
    unitPrice: 20,
    totalPrice: 200,
    branch: "Sucursal C",
  },
  {
    id: "8",
    date: "2025-10-05",
    product: "CAMISAS",
    category: "Camisas",
    clientType: "Hombre",
    size: "M",
    quantity: 2,
    unitPrice: 70,
    totalPrice: 140,
    branch: "Sucursal A",
  },
  {
    id: "9",
    date: "2025-10-06",
    product: "PANTALONES",
    category: "Pantalones",
    clientType: "Mujer",
    size: "L",
    quantity: 3,
    unitPrice: 75,
    totalPrice: 225,
    branch: "Sucursal B",
  },
  {
    id: "10",
    date: "2025-10-07",
    product: "ROPA DE BAÑO",
    category: "Ropa de Baño",
    clientType: "Niña",
    size: "12",
    quantity: 1,
    unitPrice: 40,
    totalPrice: 40,
    branch: "Sucursal C",
  },
  {
    id: "11",
    date: "2025-09-01",
    product: "ABRIGO",
    category: "Abrigos",
    clientType: "Mujer",
    size: "S",
    quantity: 3,
    unitPrice: 120,
    totalPrice: 360,
    branch: "Sucursal A",
  },
  {
    id: "12",
    date: "2025-09-02",
    product: "JEANS TERMINADOS",
    category: "Pantalones",
    clientType: "Hombre",
    size: "M",
    quantity: 5,
    unitPrice: 80,
    totalPrice: 400,
    branch: "Sucursal B",
  },
  {
    id: "13",
    date: "2025-09-03",
    product: "TSHIRT TERMINADA",
    category: "T-Shirts",
    clientType: "Niño",
    size: "10",
    quantity: 8,
    unitPrice: 25,
    totalPrice: 200,
    branch: "Sucursal A",
  },
  {
    id: "14",
    date: "2025-09-04",
    product: "VESTIDOS",
    category: "Vestidos",
    clientType: "Niña",
    size: "12",
    quantity: 3,
    unitPrice: 60,
    totalPrice: 180,
    branch: "Sucursal C",
  },
  {
    id: "15",
    date: "2025-09-05",
    product: "BUZO",
    category: "Buzos",
    clientType: "Hombre",
    size: "L",
    quantity: 2,
    unitPrice: 90,
    totalPrice: 180,
    branch: "Sucursal B",
  },
];
